// @flow
declare function getBackgroundColor(opacity?: number): string;
declare function getBackgroundLightColor(opacity?: number): string;
declare function getBackgroundDarkColor(opacity?: number): string;
declare function getWarningColor(opacity?: number): string;
declare function getWarningDarkColor(opacity?: number): string;
declare function getFatalColor(opacity?: number): string;
declare function getFatalDarkColor(opacity?: number): string;
declare function getErrorColor(opacity?: number): string;
declare function getErrorDarkColor(opacity?: number): string;
declare function getLogColor(opacity?: number): string;
declare function getWarningHighlightColor(opacity?: number): string;
declare function getDividerColor(opacity?: number): string;
declare function getHighlightColor(opacity?: number): string;
declare function getTextColor(opacity?: number): string;
export { getBackgroundColor };
export { getBackgroundLightColor };
export { getBackgroundDarkColor };
export { getWarningColor };
export { getWarningDarkColor };
export { getFatalColor };
export { getFatalDarkColor };
export { getErrorColor };
export { getErrorDarkColor };
export { getLogColor };
export { getWarningHighlightColor };
export { getDividerColor };
export { getHighlightColor };
export { getTextColor };