import { $PropertyType } from "utility-types";
// @flow
import AccessibilityInfo$f2tTypeof from "./Libraries/Components/AccessibilityInfo/AccessibilityInfo";
export declare type AccessibilityInfo = typeof AccessibilityInfo$f2tTypeof;
import ActivityIndicator$f2tTypeof from "./Libraries/Components/ActivityIndicator/ActivityIndicator";
export declare type ActivityIndicator = typeof ActivityIndicator$f2tTypeof;
import Button$f2tTypeof from "./Libraries/Components/Button";
declare type Button = typeof Button$f2tTypeof;
import DatePickerIOS$f2tTypeof from "./Libraries/Components/DatePicker/DatePickerIOS";
declare type DatePickerIOS = typeof DatePickerIOS$f2tTypeof;
import FlatList$f2tTypeof from "./Libraries/Lists/FlatList";
declare type FlatList = typeof FlatList$f2tTypeof;
import Image$f2tTypeof from "./Libraries/Image/Image";
export declare type Image = typeof Image$f2tTypeof;
import ImageBackground$f2tTypeof from "./Libraries/Image/ImageBackground";
declare type ImageBackground = typeof ImageBackground$f2tTypeof;
import InputAccessoryView$f2tTypeof from "./Libraries/Components/TextInput/InputAccessoryView";
declare type InputAccessoryView = typeof InputAccessoryView$f2tTypeof;
import KeyboardAvoidingView$f2tTypeof from "./Libraries/Components/Keyboard/KeyboardAvoidingView";
declare type KeyboardAvoidingView = typeof KeyboardAvoidingView$f2tTypeof;
import MaskedViewIOS$f2tTypeof from "./Libraries/Components/MaskedView/MaskedViewIOS";
declare type MaskedViewIOS = typeof MaskedViewIOS$f2tTypeof;
import Modal$f2tTypeof from "./Libraries/Modal/Modal";
declare type Modal = typeof Modal$f2tTypeof;
import Picker$f2tTypeof from "./Libraries/Components/Picker/Picker";
declare type Picker = typeof Picker$f2tTypeof;
import PickerIOS$f2tTypeof from "./Libraries/Components/Picker/PickerIOS";
declare type PickerIOS = typeof PickerIOS$f2tTypeof;
import Pressable$f2tTypeof from "./Libraries/Components/Pressable/Pressable";
export declare type Pressable = typeof Pressable$f2tTypeof;
import ProgressViewIOS$f2tTypeof from "./Libraries/Components/ProgressViewIOS/ProgressViewIOS";
export declare type ProgressViewIOS = typeof ProgressViewIOS$f2tTypeof;
import RefreshControl$f2tTypeof from "./Libraries/Components/RefreshControl/RefreshControl";
declare type RefreshControl = typeof RefreshControl$f2tTypeof;
import SafeAreaView$f2tTypeof from "./Libraries/Components/SafeAreaView/SafeAreaView";
export declare type SafeAreaView = typeof SafeAreaView$f2tTypeof;
import ScrollView$f2tTypeof from "./Libraries/Components/ScrollView/ScrollView";
export declare type ScrollView = typeof ScrollView$f2tTypeof;
import SectionList$f2tTypeof from "./Libraries/Lists/SectionList";
declare type SectionList = typeof SectionList$f2tTypeof;
import SegmentedControlIOS$f2tTypeof from "./Libraries/Components/SegmentedControlIOS/SegmentedControlIOS";
export declare type SegmentedControlIOS = typeof SegmentedControlIOS$f2tTypeof;
import Slider$f2tTypeof from "./Libraries/Components/Slider/Slider";
export declare type Slider = typeof Slider$f2tTypeof;
import StatusBar$f2tTypeof from "./Libraries/Components/StatusBar/StatusBar";
declare type StatusBar = typeof StatusBar$f2tTypeof;
import Switch$f2tTypeof from "./Libraries/Components/Switch/Switch";
declare type Switch = typeof Switch$f2tTypeof;
import Text$f2tTypeof from "./Libraries/Text/Text";
export declare type Text = typeof Text$f2tTypeof;
import TextInput$f2tTypeof from "./Libraries/Components/TextInput/TextInput";
export declare type TextInput = typeof TextInput$f2tTypeof;
import Touchable$f2tTypeof from "./Libraries/Components/Touchable/Touchable";
export declare type Touchable = typeof Touchable$f2tTypeof;
import TouchableHighlight$f2tTypeof from "./Libraries/Components/Touchable/TouchableHighlight";
export declare type TouchableHighlight = typeof TouchableHighlight$f2tTypeof;
import TouchableNativeFeedback$f2tTypeof from "./Libraries/Components/Touchable/TouchableNativeFeedback";
declare type TouchableNativeFeedback = typeof TouchableNativeFeedback$f2tTypeof;
import TouchableOpacity$f2tTypeof from "./Libraries/Components/Touchable/TouchableOpacity";
export declare type TouchableOpacity = typeof TouchableOpacity$f2tTypeof;
import TouchableWithoutFeedback$f2tTypeof from "./Libraries/Components/Touchable/TouchableWithoutFeedback";
declare type TouchableWithoutFeedback = typeof TouchableWithoutFeedback$f2tTypeof;
import View$f2tTypeof from "./Libraries/Components/View/View";
export declare type View = typeof View$f2tTypeof;
import VirtualizedList$f2tTypeof from "./Libraries/Lists/VirtualizedList";
declare type VirtualizedList = typeof VirtualizedList$f2tTypeof;
import VirtualizedSectionList$f2tTypeof from "./Libraries/Lists/VirtualizedSectionList";
declare type VirtualizedSectionList = typeof VirtualizedSectionList$f2tTypeof;
import ActionSheetIOS$f2tTypeof from "./Libraries/ActionSheetIOS/ActionSheetIOS";
export declare type ActionSheetIOS = typeof ActionSheetIOS$f2tTypeof;
import Alert$f2tTypeof from "./Libraries/Alert/Alert";
declare type Alert = typeof Alert$f2tTypeof;
import * as Animated$f2tTypeof from "./Libraries/Animated/Animated";
export declare type Animated = typeof Animated$f2tTypeof;
import Appearance$f2tTypeof from "./Libraries/Utilities/Appearance";
export declare type Appearance = typeof Appearance$f2tTypeof;
import AppRegistry$f2tTypeof from "./Libraries/ReactNative/AppRegistry";
export declare type AppRegistry = typeof AppRegistry$f2tTypeof;
import AppState$f2tTypeof from "./Libraries/AppState/AppState";
export declare type AppState = typeof AppState$f2tTypeof;
import AsyncStorage$f2tTypeof from "./Libraries/Storage/AsyncStorage";
export declare type AsyncStorage = typeof AsyncStorage$f2tTypeof;
import BackHandler$f2tTypeof from "./Libraries/Utilities/BackHandler";
export declare type BackHandler = typeof BackHandler$f2tTypeof;
import Clipboard$f2tTypeof from "./Libraries/Components/Clipboard/Clipboard";
export declare type Clipboard = typeof Clipboard$f2tTypeof;
import DatePickerAndroid$f2tTypeof from "./Libraries/Components/DatePickerAndroid/DatePickerAndroid";
declare type DatePickerAndroid = typeof DatePickerAndroid$f2tTypeof;
import DeviceInfo$f2tTypeof from "./Libraries/Utilities/DeviceInfo";
export declare type DeviceInfo = typeof DeviceInfo$f2tTypeof;
import DevSettings$f2tTypeof from "./Libraries/Utilities/DevSettings";
export declare type DevSettings = typeof DevSettings$f2tTypeof;
import Dimensions$f2tTypeof from "./Libraries/Utilities/Dimensions";
declare type Dimensions = typeof Dimensions$f2tTypeof;
import Easing$f2tTypeof from "./Libraries/Animated/Easing";
declare type Easing = typeof Easing$f2tTypeof;
import ReactNative$f2tTypeof from "./Libraries/Renderer/shims/ReactNative";
declare type ReactNative = typeof ReactNative$f2tTypeof;
import I18nManager$f2tTypeof from "./Libraries/ReactNative/I18nManager";
export declare type I18nManager = typeof I18nManager$f2tTypeof;
import ImagePickerIOS$f2tTypeof from "./Libraries/Image/ImagePickerIOS";
export declare type ImagePickerIOS = typeof ImagePickerIOS$f2tTypeof;
import InteractionManager$f2tTypeof from "./Libraries/Interaction/InteractionManager";
export declare type InteractionManager = typeof InteractionManager$f2tTypeof;
import Keyboard$f2tTypeof from "./Libraries/Components/Keyboard/Keyboard";
declare type Keyboard = typeof Keyboard$f2tTypeof;
import LayoutAnimation$f2tTypeof from "./Libraries/LayoutAnimation/LayoutAnimation";
export declare type LayoutAnimation = typeof LayoutAnimation$f2tTypeof;
import Linking$f2tTypeof from "./Libraries/Linking/Linking";
declare type Linking = typeof Linking$f2tTypeof;
import LogBox$f2tTypeof from "./Libraries/LogBox/LogBox";
export declare type LogBox = typeof LogBox$f2tTypeof;
import NativeDialogManagerAndroid$f2tTypeof from "./Libraries/NativeModules/specs/NativeDialogManagerAndroid";
export declare type NativeDialogManagerAndroid = typeof NativeDialogManagerAndroid$f2tTypeof;
import NativeEventEmitter$f2tTypeof from "./Libraries/EventEmitter/NativeEventEmitter";
declare type NativeEventEmitter = typeof NativeEventEmitter$f2tTypeof;
import Networking$f2tTypeof from "./Libraries/Network/RCTNetworking";
declare type Networking = typeof Networking$f2tTypeof;
import PanResponder$f2tTypeof from "./Libraries/Interaction/PanResponder";
export declare type PanResponder = typeof PanResponder$f2tTypeof;
import PermissionsAndroid$f2tTypeof from "./Libraries/PermissionsAndroid/PermissionsAndroid";
declare type PermissionsAndroid = typeof PermissionsAndroid$f2tTypeof;
import PixelRatio$f2tTypeof from "./Libraries/Utilities/PixelRatio";
declare type PixelRatio = typeof PixelRatio$f2tTypeof;
import PushNotificationIOS$f2tTypeof from "./Libraries/PushNotificationIOS/PushNotificationIOS";
declare type PushNotificationIOS = typeof PushNotificationIOS$f2tTypeof;
import Settings$f2tTypeof from "./Libraries/Settings/Settings";
export declare type Settings = typeof Settings$f2tTypeof;
import Share$f2tTypeof from "./Libraries/Share/Share";
declare type Share = typeof Share$f2tTypeof;
import StatusBarIOS$f2tTypeof from "./Libraries/Components/StatusBar/StatusBarIOS";
declare type StatusBarIOS = typeof StatusBarIOS$f2tTypeof;
import StyleSheet$f2tTypeof from "./Libraries/StyleSheet/StyleSheet";
export declare type StyleSheet = typeof StyleSheet$f2tTypeof;
import Systrace$f2tTypeof from "./Libraries/Performance/Systrace";
export declare type Systrace = typeof Systrace$f2tTypeof;
import * as TurboModuleRegistry from "./Libraries/TurboModule/TurboModuleRegistry";
import UIManager$f2tTypeof from "./Libraries/ReactNative/UIManager";
export declare type UIManager = typeof UIManager$f2tTypeof;
import useColorScheme$f2tTypeof from "./Libraries/Utilities/useColorScheme";
export declare type useColorScheme = typeof useColorScheme$f2tTypeof;
import useWindowDimensions$f2tTypeof from "./Libraries/Utilities/useWindowDimensions";
export declare type useWindowDimensions = typeof useWindowDimensions$f2tTypeof;
import UTFSequence$f2tTypeof from "./Libraries/UTFSequence";
export declare type UTFSequence = typeof UTFSequence$f2tTypeof;
import Vibration$f2tTypeof from "./Libraries/Vibration/Vibration";
export declare type Vibration = typeof Vibration$f2tTypeof;
import YellowBox$f2tTypeof from "./Libraries/YellowBox/YellowBoxDeprecated";
export declare type YellowBox = typeof YellowBox$f2tTypeof;
import { DynamicColorIOS as DynamicColorIOS$f2tTypeof } from "./Libraries/StyleSheet/PlatformColorValueTypesIOS";
export declare type DynamicColorIOS = typeof DynamicColorIOS$f2tTypeof;
import NativeModules$f2tTypeof from "./Libraries/BatchedBridge/NativeModules";
export declare type NativeModules = typeof NativeModules$f2tTypeof;
import Platform$f2tTypeof from "./Libraries/Utilities/Platform";
export declare type Platform = typeof Platform$f2tTypeof;
import { PlatformColor as PlatformColor$f2tTypeof } from "./Libraries/StyleSheet/PlatformColorValueTypes";
export declare type PlatformColor = typeof PlatformColor$f2tTypeof;
import processColor$f2tTypeof from "./Libraries/StyleSheet/processColor";
export declare type processColor = typeof processColor$f2tTypeof;
import RCTDeviceEventEmitter$f2tTypeof from "./Libraries/EventEmitter/RCTDeviceEventEmitter";
declare type RCTDeviceEventEmitter = typeof RCTDeviceEventEmitter$f2tTypeof;
import RCTNativeAppEventEmitter$f2tTypeof from "./Libraries/EventEmitter/RCTNativeAppEventEmitter";
declare type RCTNativeAppEventEmitter = typeof RCTNativeAppEventEmitter$f2tTypeof;
import { RootTagContext as RootTagContext$f2tTypeof } from "./Libraries/ReactNative/RootTag";
declare type RootTagContext = typeof RootTagContext$f2tTypeof;
import DeprecatedEdgeInsetsPropType$f2tTypeof from "./Libraries/DeprecatedPropTypes/DeprecatedEdgeInsetsPropType";
declare type DeprecatedEdgeInsetsPropType = typeof DeprecatedEdgeInsetsPropType$f2tTypeof;
import DeprecatedPointPropType$f2tTypeof from "./Libraries/DeprecatedPropTypes/DeprecatedPointPropType";
declare type DeprecatedPointPropType = typeof DeprecatedPointPropType$f2tTypeof;
import DeprecatedViewPropTypes$f2tTypeof from "./Libraries/DeprecatedPropTypes/DeprecatedViewPropTypes";
declare type DeprecatedViewPropTypes = typeof DeprecatedViewPropTypes$f2tTypeof;
import { HostComponent as _HostComponentInternal } from "./Libraries/Renderer/shims/ReactNativeTypes";
declare type HostComponent<T> = _HostComponentInternal<T>;
export type { HostComponent };
declare const $f2d_findNodeHandle: $PropertyType<ReactNative, "findNodeHandle">;
declare const $f2d_TurboModuleRegistry: typeof TurboModuleRegistry;
declare const $f2d_unstable_batchedUpdates: $PropertyType<ReactNative, "unstable_batchedUpdates">;
declare const $f2d_requireNativeComponent: <T>(uiViewClassName: string) => HostComponent<T>;
declare const $f2d_unstable_enableLogBox: () => void;
export type unstable_RootTagContext = RootTagContext;
export type EdgeInsetsPropType = DeprecatedEdgeInsetsPropType;
export type PointPropType = DeprecatedPointPropType;
export type ViewPropTypes = DeprecatedViewPropTypes;
export { AccessibilityInfo$f2tTypeof as AccessibilityInfo, ActivityIndicator$f2tTypeof as ActivityIndicator, Button$f2tTypeof as Button, DatePickerIOS$f2tTypeof as DatePickerIOS, FlatList$f2tTypeof as FlatList, Image$f2tTypeof as Image, ImageBackground$f2tTypeof as ImageBackground, InputAccessoryView$f2tTypeof as InputAccessoryView, KeyboardAvoidingView$f2tTypeof as KeyboardAvoidingView, MaskedViewIOS$f2tTypeof as MaskedViewIOS, Modal$f2tTypeof as Modal, Picker$f2tTypeof as Picker, PickerIOS$f2tTypeof as PickerIOS, Pressable$f2tTypeof as Pressable, ProgressViewIOS$f2tTypeof as ProgressViewIOS, RefreshControl$f2tTypeof as RefreshControl, SafeAreaView$f2tTypeof as SafeAreaView, ScrollView$f2tTypeof as ScrollView, SectionList$f2tTypeof as SectionList, SegmentedControlIOS$f2tTypeof as SegmentedControlIOS, Slider$f2tTypeof as Slider, StatusBar$f2tTypeof as StatusBar, Switch$f2tTypeof as Switch, Text$f2tTypeof as Text, TextInput$f2tTypeof as TextInput, Touchable$f2tTypeof as Touchable, TouchableHighlight$f2tTypeof as TouchableHighlight, TouchableNativeFeedback$f2tTypeof as TouchableNativeFeedback, TouchableOpacity$f2tTypeof as TouchableOpacity, TouchableWithoutFeedback$f2tTypeof as TouchableWithoutFeedback, View$f2tTypeof as View, VirtualizedList$f2tTypeof as VirtualizedList, VirtualizedSectionList$f2tTypeof as VirtualizedSectionList, ActionSheetIOS$f2tTypeof as ActionSheetIOS, Alert$f2tTypeof as Alert, Animated$f2tTypeof as Animated, Appearance$f2tTypeof as Appearance, AppRegistry$f2tTypeof as AppRegistry, AppState$f2tTypeof as AppState, AsyncStorage$f2tTypeof as AsyncStorage, BackHandler$f2tTypeof as BackHandler, Clipboard$f2tTypeof as Clipboard, DatePickerAndroid$f2tTypeof as DatePickerAndroid, DeviceInfo$f2tTypeof as DeviceInfo, DevSettings$f2tTypeof as DevSettings, Dimensions$f2tTypeof as Dimensions, Easing$f2tTypeof as Easing, $f2d_findNodeHandle as findNodeHandle, I18nManager$f2tTypeof as I18nManager, ImagePickerIOS$f2tTypeof as ImagePickerIOS, InteractionManager$f2tTypeof as InteractionManager, Keyboard$f2tTypeof as Keyboard, LayoutAnimation$f2tTypeof as LayoutAnimation, Linking$f2tTypeof as Linking, LogBox$f2tTypeof as LogBox, NativeDialogManagerAndroid$f2tTypeof as NativeDialogManagerAndroid, NativeEventEmitter$f2tTypeof as NativeEventEmitter, Networking$f2tTypeof as Networking, PanResponder$f2tTypeof as PanResponder, PermissionsAndroid$f2tTypeof as PermissionsAndroid, PixelRatio$f2tTypeof as PixelRatio, PushNotificationIOS$f2tTypeof as PushNotificationIOS, Settings$f2tTypeof as Settings, Share$f2tTypeof as Share, StatusBarIOS$f2tTypeof as StatusBarIOS, StyleSheet$f2tTypeof as StyleSheet, Systrace$f2tTypeof as Systrace, $f2d_TurboModuleRegistry as TurboModuleRegistry, UIManager$f2tTypeof as UIManager, $f2d_unstable_batchedUpdates as unstable_batchedUpdates, useColorScheme$f2tTypeof as useColorScheme, useWindowDimensions$f2tTypeof as useWindowDimensions, UTFSequence$f2tTypeof as UTFSequence, Vibration$f2tTypeof as Vibration, YellowBox$f2tTypeof as YellowBox, RCTDeviceEventEmitter$f2tTypeof as DeviceEventEmitter, DynamicColorIOS$f2tTypeof as DynamicColorIOS, RCTNativeAppEventEmitter$f2tTypeof as NativeAppEventEmitter, NativeModules$f2tTypeof as NativeModules, Platform$f2tTypeof as Platform, PlatformColor$f2tTypeof as PlatformColor, processColor$f2tTypeof as processColor, $f2d_requireNativeComponent as requireNativeComponent, RootTagContext$f2tTypeof as unstable_RootTagContext, $f2d_unstable_enableLogBox as unstable_enableLogBox, DeprecatedEdgeInsetsPropType$f2tTypeof as EdgeInsetsPropType, DeprecatedPointPropType$f2tTypeof as PointPropType, DeprecatedViewPropTypes$f2tTypeof as ViewPropTypes };
declare const $f2tExportDefault:
/*[FLOW2DTS - Warning] This type was an exact object type in the original Flow source.*/
{
  AccessibilityInfo: AccessibilityInfo;
  ActivityIndicator: ActivityIndicator;
  Button: Button;
  DatePickerIOS: DatePickerIOS;
  FlatList: FlatList;
  Image: Image;
  ImageBackground: ImageBackground;
  InputAccessoryView: InputAccessoryView;
  KeyboardAvoidingView: KeyboardAvoidingView;
  MaskedViewIOS: MaskedViewIOS;
  Modal: Modal;
  Picker: Picker;
  PickerIOS: PickerIOS;
  Pressable: Pressable;
  ProgressViewIOS: ProgressViewIOS;
  RefreshControl: RefreshControl;
  SafeAreaView: SafeAreaView;
  ScrollView: ScrollView;
  SectionList: SectionList;
  SegmentedControlIOS: SegmentedControlIOS;
  Slider: Slider;
  StatusBar: StatusBar;
  Switch: Switch;
  Text: Text;
  TextInput: TextInput;
  Touchable: Touchable;
  TouchableHighlight: TouchableHighlight;
  TouchableNativeFeedback: TouchableNativeFeedback;
  TouchableOpacity: TouchableOpacity;
  TouchableWithoutFeedback: TouchableWithoutFeedback;
  View: View;
  VirtualizedList: VirtualizedList;
  VirtualizedSectionList: VirtualizedSectionList;
  ActionSheetIOS: ActionSheetIOS;
  Alert: Alert;
  Animated: Animated;
  Appearance: Appearance;
  AppRegistry: AppRegistry;
  AppState: AppState;
  AsyncStorage: AsyncStorage;
  BackHandler: BackHandler;
  Clipboard: Clipboard;
  DatePickerAndroid: DatePickerAndroid;
  DeviceInfo: DeviceInfo;
  DevSettings: DevSettings;
  Dimensions: Dimensions;
  Easing: Easing;
  findNodeHandle: $PropertyType<ReactNative, "findNodeHandle">;
  I18nManager: I18nManager;
  ImagePickerIOS: ImagePickerIOS;
  InteractionManager: InteractionManager;
  Keyboard: Keyboard;
  LayoutAnimation: LayoutAnimation;
  Linking: Linking;
  LogBox: LogBox;
  NativeDialogManagerAndroid: NativeDialogManagerAndroid;
  NativeEventEmitter: NativeEventEmitter;
  Networking: Networking;
  PanResponder: PanResponder;
  PermissionsAndroid: PermissionsAndroid;
  PixelRatio: PixelRatio;
  PushNotificationIOS: PushNotificationIOS;
  Settings: Settings;
  Share: Share;
  StatusBarIOS: StatusBarIOS;
  StyleSheet: StyleSheet;
  Systrace: Systrace;
  TurboModuleRegistry: typeof TurboModuleRegistry;
  UIManager: UIManager;
  unstable_batchedUpdates: $PropertyType<ReactNative, "unstable_batchedUpdates">;
  useColorScheme: useColorScheme;
  useWindowDimensions: useWindowDimensions;
  UTFSequence: UTFSequence;
  Vibration: Vibration;
  YellowBox: YellowBox;
  DeviceEventEmitter: RCTDeviceEventEmitter;
  DynamicColorIOS: DynamicColorIOS;
  NativeAppEventEmitter: RCTNativeAppEventEmitter;
  NativeModules: NativeModules;
  Platform: Platform;
  PlatformColor: PlatformColor;
  processColor: processColor;
  requireNativeComponent: <T>(uiViewClassName: string) => HostComponent<T>;
  unstable_RootTagContext: RootTagContext;
  unstable_enableLogBox: () => void;
  EdgeInsetsPropType: DeprecatedEdgeInsetsPropType;
  PointPropType: DeprecatedPointPropType;
  ViewPropTypes: DeprecatedViewPropTypes;
};
export default $f2tExportDefault;
export * from "./TypeScriptSupplementals";