name: CI
on: [push, pull_request]
jobs:
  PR:
    name: Validation
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn install --frozen-lockfile
      - run: npx beachball check --branch origin/${{ github.base_ref }} --changehint "Run `yarn change` from root of repo to generate a change file."
      - run: yarn build
      - run: yarn test